# Generated by Django 4.1.5 on 2023-03-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_first_remove_category_name_category_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='first',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
