# Generated by Django 4.1.5 on 2023-03-06 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_delete_first_alter_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
