# Generated by Django 4.1.5 on 2023-03-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='clay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pottery_machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
    ]
