# Generated by Django 4.1.5 on 2023-03-15 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_clay_fixture_pottery_machine_remove_category_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clay',
        ),
        migrations.DeleteModel(
            name='fixture',
        ),
        migrations.DeleteModel(
            name='pottery_machine',
        ),
    ]
