# Generated by Django 4.1.5 on 2023-03-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_delete_clay_delete_fixture_delete_pottery_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_name',
            field=models.CharField(default='category', max_length=100),
        ),
    ]
