# Generated by Django 4.1.5 on 2023-03-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_category_product_category_category_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='product_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='product_type',
            field=models.CharField(max_length=100),
        ),
    ]
