# Generated by Django 4.1.5 on 2023-03-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_category_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='glina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='shit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roduct_type', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='product_type',
        ),
    ]
