# Generated by Django 4.1.5 on 2023-03-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_glina_shit_remove_category_product_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='glina',
        ),
        migrations.DeleteModel(
            name='shit',
        ),
        migrations.AddField(
            model_name='category',
            name='product_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='roduct_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
