# Generated by Django 4.1.5 on 2023-03-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_delete_glina_delete_shit_category_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
