# Generated by Django 4.1.5 on 2023-03-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_category_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
    ]
