# Generated by Django 4.2 on 2023-04-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_product_category_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='product_price',
            field=models.IntegerField(default=None),
        ),
    ]
