# Generated by Django 4.2 on 2023-04-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_category_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_sum', models.CharField(default={'product_price__sum': 30}, max_length=225)),
            ],
        ),
    ]
