# Generated by Django 4.2 on 2023-04-13 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='basket',
        ),
    ]
