# Generated by Django 4.2 on 2023-04-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
